# Generated by Django 4.2.7 on 2023-12-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_shippingtax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.TextField(default='mobile money', max_length=100),
        ),
    ]
