# Generated by Django 4.2.7 on 2023-11-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(default='Adenta Madina', max_length=20),
        ),
    ]
