# Generated by Django 4.2.7 on 2023-11-16 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
