# Generated by Django 4.2.7 on 2023-12-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_total_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Confirm'), ('delivery', 'Delivery'), ('delivered', 'Delivered')], default='pending', max_length=100),
        ),
    ]
