# Generated by Django 4.2.7 on 2023-12-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_location_shippingrate_nearest_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingrate',
            name='country',
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='region',
            field=models.CharField(choices=[('region1', 'Region 1'), ('region2', 'Region 2'), ('region3', 'Region 3')], max_length=100),
        ),
    ]
