# Generated by Django 4.2.7 on 2023-12-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_shippingrate_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingrate',
            name='city',
            field=models.CharField(default='please add a ciy', max_length=100),
        ),
    ]
