# Generated by Django 4.2.7 on 2023-12-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_shippingrate_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingrate',
            options={'ordering': ['region', 'city']},
        ),
    ]
