# Generated by Django 4.2.7 on 2023-12-26 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_shippingrate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingrate',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
