# Generated by Django 4.2.7 on 2023-12-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_shippingrate_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingrate',
            name='city',
            field=models.CharField(choices=[('Ashanti Region', 'Cites in Ashanti Region'), ('Kumasi', 'Kumasi'), ('Obuasi', 'Obuasi'), ('Ejisu', 'Ejisu'), ('Tafo', 'Tafo'), ('Asokore Mampong', 'Asokore Mampong'), ('Asante Mampong', 'Asante Mampong'), ('Konongo', 'Konongo'), ('Agogo', 'Agogo'), ('Bekwai', 'Bekwai'), ('Nkawie', 'Nkawie'), ('Fomena', 'Fomena'), ('Mampong', 'Mampong'), ('Tepa', 'Tepa'), ('Juaso', 'Juaso'), ('Effiduase', 'Effiduase'), ('Bekwai', 'Bekwai'), ('New Edubiase', 'New Edubiase'), ('Kumawu', 'Kumawu'), ('Agona', 'Agona'), ('Afigya Kwabre', 'Afigya Kwabre')], max_length=100),
        ),
    ]
