# Generated by Django 4.2.7 on 2023-12-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_shippingrate_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingtax',
            name='shipping',
        ),
    ]
