# Generated by Django 4.2.7 on 2024-02-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_cartproductsize_size_product_has_sizes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
