# Generated by Django 4.2.7 on 2024-02-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item_size',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='CartProductSize',
        ),
    ]
