# Generated by Django 4.2.7 on 2024-02-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_cartitem_item_size_delete_cartproductsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_product_size', models.CharField(max_length=50)),
            ],
        ),
    ]
