# Generated by Django 4.2.7 on 2024-02-10 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_cartproductsize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartProductSize',
        ),
    ]
