# Generated by Django 4.2.7 on 2024-02-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='display_text',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
