# Generated by Django 4.2.7 on 2024-02-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_product_size_maincategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincategory',
            old_name='sub_category',
            new_name='sub_categories',
        ),
    ]
