# Generated by Django 4.2.7 on 2024-02-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_rename_sub_category_maincategory_sub_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discound',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='has_discound',
            field=models.BooleanField(default=False),
        ),
    ]
