# Generated by Django 4.2.7 on 2024-02-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_product_discound_product_has_discound'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discound',
            new_name='discount',
        ),
    ]
