# Generated by Django 4.2.7 on 2024-02-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_rename_discound_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_discound',
            new_name='has_discount',
        ),
    ]
