# Generated by Django 4.2.7 on 2023-11-25 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_messages_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_received',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
