# Generated by Django 4.2.7 on 2023-12-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_address_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(help_text='please enter an address to recieve notifications', max_length=100, null=True),
        ),
    ]
