# Generated by Django 4.2.7 on 2023-12-09 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_customer_address_alter_customer_location_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='AdminEmail',
        ),
        migrations.RenameModel(
            old_name='PhoneNumber',
            new_name='AdminPhoneNumber',
        ),
        migrations.DeleteModel(
            name='AdminContact',
        ),
    ]
