# Generated by Django 4.2.7 on 2023-12-09 16:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_rename_email_adminemail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminEmail',
        ),
        migrations.DeleteModel(
            name='AdminPhoneNumber',
        ),
    ]
