# Generated by Django 4.2.7 on 2023-12-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_admincontacts_delete_adminemail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminContacts',
            new_name='AdminContact',
        ),
    ]
