# Generated by Django 4.2.7 on 2023-12-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_rename_admincontacts_admincontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='location',
            new_name='region',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(help_text='Please this field is required', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='nearest_location',
            field=models.CharField(help_text='Please this field is required', max_length=100, null=True),
        ),
    ]
