REGION_CHOICES = [
        ('Ashanti Region', 'Ashanti Region'),
        ('Brong-Ahafo Region', 'Brong-Ahafo Region'),
        ('Central Region', 'Central Region'),
        ('Eastern Region', 'Eastern Region'),
        ('Greater Accra Region', 'Greater Accra Region'),
        ('Northern Region', 'Northern Region'),
        ('Upper East Region', 'Upper East Region'),
        ('Upper West Region', 'Upper West Region'),
        ('Volta Region', 'Volta Region'),
        ('Western Region', 'Western Region'),
        ('Western North Region', 'Western North Region'),
        ('Oti Region', 'Oti Region'),
        ('Savannah Region', 'Savannah Region'),
        ('North East Region', 'North East Region'),
        ('Bono Region', 'Bono Region'),
        ('Ahafo Region', 'Ahafo Region')
    ]

CITES_IN_REGION = [
        ( 'Ashanti Region', 'Cites in Ashanti Region'),
        ('Kumasi', 'Kumasi'),
        ('Obuasi', 'Obuasi'),
        ('Ejisu', 'Ejisu'),
        ('Tafo', 'Tafo'),
        ('Asokore Mampong', 'Asokore Mampong'),
        ('Asante Mampong', 'Asante Mampong'),
        ('Konongo', 'Konongo'),
        ('Agogo', 'Agogo'),
        ('Bekwai', 'Bekwai'),
        ('Nkawie', 'Nkawie'),
        ('Fomena', 'Fomena'),
        ('Mampong', 'Mampong'),
        ('Tepa', 'Tepa'),
        ('Juaso', 'Juaso'),
        ('Effiduase', 'Effiduase'),
        ('Bekwai', 'Bekwai'),
        ('New Edubiase', 'New Edubiase'),
        ('Kumawu', 'Kumawu'),
        ('Agona', 'Agona'),
        ('Afigya Kwabre', 'Afigya Kwabre'),
        # this cities in Brong_Ahafo
        ("-", "----------------------------"),
        ('Sunyani', 'Cities in Brong-Ahafo Region'),
        ('Sunyani', 'Sunyani'),
        ('Techiman', 'Techiman'),
        ('Wenchi', 'Wenchi'),
        ('Berekum', 'Berekum'),
        ('Dormaa Ahenkro', 'Dormaa Ahenkro'),
        ('Nkoranza', 'Nkoranza'),
        ('Bechem', 'Bechem'),
        ('Kintampo', 'Kintampo'),
        ('Goaso', 'Goaso'),
        ('Atebubu', 'Atebubu'),
        ('Duayaw Nkwanta', 'Duayaw Nkwanta'),
        ('Sampa', 'Sampa'),
        ('Japekrom', 'Japekrom'),
        ('Chiraa', 'Chiraa'),
        ('Kwatire', 'Kwatire'),
        ('Yeji', 'Yeji'),
        ('Drobo', 'Drobo'),
        ('Fiapre', 'Fiapre'),
        ('Odumase', 'Odumase'),
        ('Nyomoase', 'Nyomoase'),
        # This is cities in Central Region
        ("-", "----------------------------"),
        ("Cape Coast", "Cities in Cape Coast"),
        ("Cape Coast", "Cape Coast"),
        ("Elmina", "Elmina"),
        ("Winneba", "Winneba"),
        ("Mankessim", "Mankessim"),
        ("Agona Swedru", "Agona Swedru"),
        ("Saltpond", "Saltpond"),
        ("Kasoa", "Kasoa"),
        ("Twifo Praso", "Twifo Praso"),
        ("Assin Fosu", "Assin Fosu"),
        ("Abura-Dunkwa", "Abura-Dunkwa"),
        ("Dunkwa-on-Offin", "Dunkwa-on-Offin"),
        ("Apam", "Apam"),
        ("Breman Asikuma", "Breman Asikuma"),
        ("Biriwa", "Biriwa"),
        ("Ajumako", "Ajumako"),
        ("Ekumfi Otuam", "Ekumfi Otuam"),
        ("Gomoa Pomadze", "Gomoa Pomadze"),
        ("Abakrampa", "Abakrampa"),
        ("Anomabo", "Anomabo"),
        ("Moree", "Moree"),
        # Cities in Central Region
        ("-", "----------------------------"),
        ("Koforidua", "Cites in Eastern Region"),
        ("Koforidua", "Koforidua"),
        ("Nkawkaw", "Nkawkaw"),
        ("Mpraeso", "Mpraeso"),
        ("Somanya", "Somanya"),
        ("Akim Oda", "Akim Oda"),
        ("Akosombo", "Akosombo"),
        ("Suhum", "Suhum"),
        ("Nsawam", "Nsawam"),
        ("Asamankese", "Asamankese"),
        ("Akwatia", "Akwatia"),
        ("Aburi", "Aburi"),
        ("Kibi", "Kibi"),
        ("Adeiso", "Adeiso"),
        ("Kade", "Kade"),
        ("Akyem Swedru", "Akyem Swedru"),
        ("Akim Swedru", "Akim Swedru"),
        ("Akyem Wenchi", "Akyem Wenchi"),
        ("Begoro", "Begoro"),
        ("Apegusu", "Apegusu"),
        ("Mamfe", "Mamfe"),
        # Cities in Greater Accra Region
        ("-", "----------------------------"),
        ("Mamfe", "Cities in Greater Accra Region"),
        ("Accra", "Accra"),
        ("Tema", "Tema"),
        ("Ashaiman", "Ashaiman"),
        ("Madina", "Madina"),
        ("Teshie", "Teshie"),
        ("Nungua", "Nungua"),
        ("Adenta", "Adenta"),
        ("Dansoman", "Dansoman"),
        ("Kaneshie", "Kaneshie"),
        ("Labadi", "Labadi"),
        ("Osu", "Osu"),
        ("La", "La"),
        ("Mamprobi", "Mamprobi"),
        ("East Legon", "East Legon"),
        ("Airport Residential Area", "Airport Residential Area"),
        ("Weija", "Weija"),
        ("Korle Bu", "Korle Bu"),
        ("Abeka", "Abeka"),
        ("Kwabenya", "Kwabenya"),
        ("North Ridge", "North Ridge"),
        # Cities in Northern Region
        ("-", "----------------------------"),
        ("North Ridge", "Cities in Northern Region"),
        ("Tamale", "Tamale"),
        ("Yendi", "Yendi"),
        ("Savelugu", "Savelugu"),
        ("Bolgatanga", "Bolgatanga"),
        ("Wa", "Wa"),
        ("Navrongo", "Navrongo"),
        ("Bimbilla", "Bimbilla"),
        ("Damongo", "Damongo"),
        ("Salaga", "Salaga"),
        ("Walewale", "Walewale"),
        ("Gambaga", "Gambaga"),
        ("Kpandai", "Kpandai"),
        ("Yapei", "Yapei"),
        ("Sawla", "Sawla"),
        ("Buipe", "Buipe"),
        ("Kumbungu", "Kumbungu"),
        ("Zabzugu", "Zabzugu"),
        ("Paga", "Paga"),
        ("Bawku", "Bawku"),
        ("Tolon", "Tolon"),
        # Cities in Upper East Region
        ("-", "----------------------------"),
        ("Tolon", "Cities in Upper East Region"),
        ("Bolgatanga", "Bolgatanga"),
        ("Navrongo", "Navrongo"),
        ("Bawku", "Bawku"),
        ("Zebilla", "Zebilla"),
        ("Paga", "Paga"),
        ("Tenkudogo", "Tenkudogo"),
        ("Chiana", "Chiana"),
        ("Tumu", "Tumu"),
        ("Nangodi", "Nangodi"),
        ("Bongo", "Bongo"),
        ("Garu", "Garu"),
        ("Zuarungu", "Zuarungu"),
        ("Binduri", "Binduri"),
        ("Sandema", "Sandema"),
        ("Sirigu", "Sirigu"),
        ("Gowrie-Kunkua", "Gowrie-Kunkua"),
        ("Zorko", "Zorko"),
        ("Winkongo", "Winkongo"),
        ("Anateem", "Anateem"),
        ("Gbedembilisi", "Gbedembilisi"),
        # Cities in Upper West Region
        ("-", "----------------------------"),
        ("-", "Cities in Upper West Region"),
        ("Tumu", "Tumu"),
        ("Nandom", "Nandom"),
        ("Lawra", "Lawra"),
        ("Jirapa", "Jirapa"),
        ("Tangale", "Tangale"),
        ("Daffiama", "Daffiama"),
        ("Nadowli", "Nadowli"),
        ("Lambussie", "Lambussie"),
        ("Wechiau", "Wechiau"),
        ("Funsi", "Funsi"),
        ("Dorimon", "Dorimon"),
        ("Gwollu", "Gwollu"),
        ("Kaleo", "Kaleo"),
        ("Charia", "Charia"),
        ("Nyoli", "Nyoli"),
        ("Loggu", "Loggu"),
        ("Sankana", "Sankana"),
        ("Bussie", "Bussie"),
        ("Ko", "Ko"),
        ("-", "----------------------------"),
        ("Mamfe", "Cities in Volta Region"),
        ("Ho", "Ho"),
        ("Keta", "Keta"),
        ("Akatsi", "Akatsi"),
        ("Aflao", "Aflao"),
        ("Hohoe", "Hohoe"),
        ("Kpandu", "Kpandu"),
        ("Anloga", "Anloga"),
        ("Sogakope", "Sogakope"),
        ("Jasikan", "Jasikan"),
        ("Denu", "Denu"),
        ("Kadjebi", "Kadjebi"),
        ("Kete Krachi", "Kete Krachi"),
        ("Adidome", "Adidome"),
        ("Ave-Dakpa", "Ave-Dakpa"),
        ("Dzodze", "Dzodze"),
        ("Akrofu", "Akrofu"),
        ("Have", "Have"),
        ("Kpeve", "Kpeve"),
        ("Amedzofe", "Amedzofe"),
        ("Tongor Agorve", "Tongor Agorve"),
        ("-", "----------------------------"),
        ("Mamfe", "Cities in Western Region"),
        ("Sekondi-Takoradi", "Sekondi-Takoradi"),
        ("Tarkwa", "Tarkwa"),
        ("Axim", "Axim"),
        ("Elubo", "Elubo"),
        ("Essiama", "Essiama"),
        ("Bibiani", "Bibiani"),
        ("Enchi", "Enchi"),
        ("Nkroful", "Nkroful"),
        ("Agona Nkwanta", "Agona Nkwanta"),
        ("Daboase", "Daboase"),
        ("Shama", "Shama"),
        ("Bogoso", "Bogoso"),
        ("Prestea", "Prestea"),
        ("Mpohor", "Mpohor"),
        ("Akontombra", "Akontombra"),
        ("Asankragua", "Asankragua"),
        ("Half Assini", "Half Assini"),
        ("Sefwi-Wiawso", "Sefwi-Wiawso"),
        ("Sefwi-Bekwai", "Sefwi-Bekwai"),
        ("Ankasa", "Ankasa"),
        ("-", "----------------------------"),
        ("Mamfe", "Cities in Western North Region"),
        ("Sefwi-Wiawso", "Sefwi-Wiawso"),
        ("Bodi", "Bodi"),
        ("Bia", "Bia"),
        ("Enchi", "Enchi"),
        ("Juaboso", "Juaboso"),
        ("Sefwi-Akontombra", "Sefwi-Akontombra"),
        ("Bibiani", "Bibiani"),
        ("Awaso", "Awaso"),
        ("Asawinso", "Asawinso"),
        ("Akontombra", "Akontombra"),
        ("Suaman", "Suaman"),
        ("Anhwiaso", "Anhwiaso"),
        ("Dadieso", "Dadieso"),
        ("Debiso", "Debiso"),
        ("Sefwi-Debiso", "Sefwi-Debiso"),
        ("Sefwi-Bekwai", "Sefwi-Bekwai"),
        ("Sefwi-Dwenase", "Sefwi-Dwenase"),
        ("Adabokrom", "Adabokrom"),
        ("Asankragua", "Asankragua"),
        ("Essam", "Essam"),
        ("-", "----------------------------"),
        ("Mamfe", "Cities in Oti Region"),
        ("Dambai", "Dambai"),
        ("Jasikan", "Jasikan"),
        ("Kadjebi", "Kadjebi"),
        ("Nkwanta", "Nkwanta"),
        ("Kete Krachi", "Kete Krachi"),
        ("Kpasa", "Kpasa"),
        ("Kpassa", "Kpassa"),
        ("Worawora", "Worawora"),
        ("Buem", "Buem"),
        ("Krachi Nchumuru", "Krachi Nchumuru"),
        ("Woadze", "Woadze"),
        ("Dorfor Adidome", "Dorfor Adidome"),
        ("Bame", "Bame"),
        ("Kete", "Kete"),
        ("Bame Adidome", "Bame Adidome"),
        ("Dambai Krachi", "Dambai Krachi"),
        ("Kwamekrom", "Kwamekrom"),
        ("Dambai Nkwanta", "Dambai Nkwanta"),
        ("Dorfor", "Dorfor"),
        ("-", "----------------------------"),
        ("Mamfe", "Cities in Savannah Region"),
        ("Damongo", "Damongo"),
        ("Buipe", "Buipe"),
        ("Salaga", "Salaga"),
        ("Sawla", "Sawla"),
        ("Yapei", "Yapei"),
        ("Kpandai", "Kpandai"),
        ("Daboya", "Daboya"),
        ("Kusawgu", "Kusawgu"),
        ("Bimbago", "Bimbago"),
        ("Kalande", "Kalande"),
        ("Larabanga", "Larabanga"),
        ("Yapei Yipala", "Yapei Yipala"),
        ("Buipe Kpandai", "Buipe Kpandai"),
        ("Daboya Mankarigu", "Daboya Mankarigu"),
        ("Sawla-Tuna-Kalba", "Sawla-Tuna-Kalba"),
        ("Fufulso", "Fufulso"),
        ("Kpembe", "Kpembe"),
        ("Kpalbe", "Kpalbe"),
        ("Kulmasa", "Kulmasa"),
        ("Buipe Yapei", "Buipe Yapei"),
        ("-", "----------------------------"),
        ("Mamfe", "Cities in North East Region"),
        ("Nalerigu", "Nalerigu"),
        ("Walewale", "Walewale"),
        ("Gambaga", "Gambaga"),
        ("Bunkpurugu", "Bunkpurugu"),
        ("Yagaba", "Yagaba"),
        ("Yendi", "Yendi"),
        ("Garu", "Garu"),
        ("Saboba", "Saboba"),
        ("Nakpanduri", "Nakpanduri"),
        ("Chereponi", "Chereponi"),
        ("Wulensi", "Wulensi"),
        ("Nantong", "Nantong"),
        ("Bimbilla", "Bimbilla"),
        ("Zabzugu", "Zabzugu"),
        ("Langbinsi", "Langbinsi"),
        ("Kpandai", "Kpandai"),
        ("Gushegu", "Gushegu"),
        ("Sakogu", "Sakogu"),
        ("Bugri", "Bugri"),
        ("Kubori", "Kubori"),
        ("-", "----------------------------"),
        ("Mamfe", "Cities in Bono Region"),
        ("Sunyani", "Sunyani"),
        ("Techiman", "Techiman"),
        ("Berekum", "Berekum"),
        ("Nkoranza", "Nkoranza"),
        ("Wenchi", "Wenchi"),
        ("Kintampo", "Kintampo"),
        ("Dormaa Ahenkro", "Dormaa Ahenkro"),
        ("Duayaw Nkwanta", "Duayaw Nkwanta"),
        ("Atebubu", "Atebubu"),
        ("Drobo", "Drobo"),
        ("Sampa", "Sampa"),
        ("Prang", "Prang"),
        ("Nsawkaw", "Nsawkaw"),
        ("Kwame Danso", "Kwame Danso"),
        ("Koase", "Koase"),
        ("Tanoso", "Tanoso"),
        ("Banda Ahenkro", "Banda Ahenkro"),
        ("Kwatire", "Kwatire"),
        ("Seikwa", "Seikwa"),
        ("Soronoase", "Soronoase"),
        ("-", "----------------------------"),
        ("Mamfe", "Cities in Ahafo Region"),
        ("Goaso", "Goaso"),
        ("Hwidiem", "Hwidiem"),
        ("Kenyasi", "Kenyasi"),
        ("Bechem", "Bechem"),
        ("Duayaw Nkwanta", "Duayaw Nkwanta"),
        ("Mim", "Mim"),
        ("Kukuom", "Kukuom"),
        ("Sankore", "Sankore"),
        ("Yamfo", "Yamfo"),
        ("Ntotroso", "Ntotroso"),
        ("Abesim", "Abesim"),
        ("Chiraa", "Chiraa"),
        ("Krom", "Krom"),
        ("Adrobaa", "Adrobaa"),
        ("Acherensua", "Acherensua"),
    ]